name: Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        scalaVersion: ["2.13.8"]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: openjdk@1.17

      # https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-


      - uses: actions/cache@v3
        name: Cache scalajs-bundler node_modules
        with:
          path: "*/target/**/main/node_modules"
          key: ${{ runner.os }}-scalajsbundler-node_modules-${{ hashFiles('*/yarn.lock') }}
          restore-keys: ${{ runner.os }}-scalajsbundler-node_modules


      - name: Compile
        run: |
          # Runner has 7G of RAM, so 4G for sbt is ok here:
          # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
          sbt --mem 4096 scalafmtCheck scalafmtSbtCheck "++${{matrix.scalaVersion}} compile"

      - name: Prepare devserver to run End-to-End UI Tests
        run: |
          # Start frontend dev-webserver
          # (ENABLE_FATAL_WARNINGS=true sbt webapp/fastOptJS/startWebpackDevServer shell || kill 0) &
          (
            cd webapp/target/scala-2.13/scalajs-bundler/main
            node node_modules/.bin/webpack-dev-server --bail --port 12345 --config  webpack.config.dev.js || kill 0
          ) &

      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0


      # - name: Debug over SSH (tmate)
      #   # if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true
